import { Component } from '@angular/core';
import { SearchBarComponent } from '../components/search-bar/search-bar.component';
import { Food } from '../models';
@Component({
  selector: 'app-search-food',
  imports: [SearchBarComponent],
  templateUrl: './search-food.component.html',
  styleUrl: './search-food.component.css',
})
export class SearchFoodComponent {
  popularFoods: Food[] = [
    {
      id: 1,
      name: 'Pechuga de pollo (100g)',
      protein: 31,
      carbs: 0,
      fats: 3.6,
      calories: 165,
      dateTime: new Date('2023-06-10T12:30:00'),
      icon: 'ep:food',
    },
    {
      id: 2,
      name: 'Salmón (100g)',
      protein: 25,
      carbs: 0,
      fats: 13,
      calories: 208,
      dateTime: new Date('2023-06-10T13:15:00'),
      icon: 'ep:food',
    },
    {
      id: 3,
      name: 'Arroz blanco (1 taza)',
      protein: 4.2,
      carbs: 45,
      fats: 0.4,
      calories: 205,
      dateTime: new Date('2023-06-10T13:20:00'),
      icon: 'ep:food',
    },
    {
      id: 4,
      name: 'Aguacate (100g)',
      protein: 2,
      carbs: 9,
      fats: 15,
      calories: 160,
      dateTime: new Date('2023-06-11T08:45:00'),
      icon: 'ep:food',
    },
    {
      id: 5,
      name: 'Huevos revueltos (2 unidades)',
      protein: 12,
      carbs: 1,
      fats: 10,
      calories: 140,
      dateTime: new Date('2023-06-11T09:00:00'),
      icon: 'ep:food',
    },
    {
      id: 6,
      name: 'Avena (1 taza cocida)',
      protein: 6,
      carbs: 27,
      fats: 3,
      calories: 150,
      dateTime: new Date('2023-06-11T07:30:00'),
      icon: 'ep:food',
    },
    {
      id: 7,
      name: 'Manzana (1 unidad)',
      protein: 0.5,
      carbs: 25,
      fats: 0.3,
      calories: 95,
      dateTime: new Date('2023-06-11T11:00:00'),
      icon: 'ep:food',
    },
    {
      id: 8,
      name: 'Batido de proteína',
      protein: 24,
      carbs: 8,
      fats: 2,
      calories: 150,
      dateTime: new Date('2023-06-11T16:30:00'),
      icon: 'ep:food',
    },
    {
      id: 9,
      name: 'Almendras (30g)',
      protein: 6,
      carbs: 6,
      fats: 14,
      calories: 170,
      dateTime: new Date('2023-06-12T10:00:00'),
      icon: 'ep:food',
    },
    {
      id: 10,
      name: 'Brócoli (100g)',
      protein: 2.8,
      carbs: 6,
      fats: 0.4,
      calories: 35,
      dateTime: new Date('2023-06-12T12:45:00'),
      icon: 'ep:food',
    },
  ];
}
